// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Sample
{

public enum Equipment : byte
{
  NONE = 0,
  Weapon = 1,
};



static public class EquipmentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Equipment)typeId)
    {
      case Equipment.Weapon:
        result = MyGame.Sample.WeaponVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
