// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame.Sample
{

public enum PacketId : int
{
  Packet = 0,
  Monster = 1,
  Weapon = 2,
  Vec3 = 3,
};


}
