// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UnitTest
{

public enum PacketId : int
{
  Packet1 = 0,
  Packet2 = 1,
};


}
